language: python
python:
- 2.7
- 3.4
before_install:
- sudo apt-get install -qq libzmq3-dev
install:
- pip install .
script:
- python -m unittest -v bookstore.tests.test_bookstore.TestSwiftNotebookManager
env:
  global:
  - secure: eoRBA3jSGuuwxAgvQOsW8Q77/9OtNF7zv3XfDpp+GilgB8pLk3ji1gBoWOFe+i7GpVcA5kC6Dr/f1bqjydokKD1sCJV58WOBHC1aD8/SMwqpVQBhw70zUEGEtCza9U8bpbclSCmF2UA1I6Dhnv5yxwkWROKMX2JnRWzdyb4NzsA=
  - secure: b8uSSHd7fYPbGoDqbwY5SWJwZ3AYpRJgej3lO2lG7TU4nhiMSaecnoLUrROBompnNHPhWKgorerdt54zsVoYnAnzC0w0supJlVWP5lZzERISWeqZ5QoqDoJCJtK+RzglzEp4MxHZDvRzzsWKJJGPYLthDFpJZiaD0Bnr3jCT41U=
  - secure: Hri7EWzQVyMktPNyIaZYJBcuFB2GlEZRuZ1GNuLqhdpDOEyh+5LRcCAw6YtR7Zb0uTT2MBJ4G1QzfSZ1Jq9W+/rcHzXHU2twDs7sGiBPoRJS9ynUZrGGyIEGAsgszp+DbNaaKHXkJQXBRd2E+7gsRMH0v4fOEOGDhcTXVZ1RQuQ=
  - secure: oWwh46XUkbCE/is/4Z54W4tFt554grAxepDg6fui8XFKOaoaO9JBrWq/keGsiCTN3tsbWrA3RDQHvC3osEeOxn88D/xcS2aHEoOze/j/z6swS6NYb1ecG1JwuyKMQrHxvJvAUX8WeMLk83n6MOBv8IZlwOHOpDsUOOMMlf5GDbk=
  - secure: GjwrbfPENzKtG24GxqNHVSW5IBh7utdl/xZvsh6NBKywjvOOjSwYCHV9cs+teHm/13v4k6hAImhzAlNC0iEW2nspqYbPsIvP8Im0ggWq/XsyoRW+aASr4KFaUnETG1eWXGMUg5hoNZzD2ZgkvWyVZU8pTDKfYfSHPuwxyXU8irU=
  - secure: P/0QU+Vm+ck1wDBDpFHrv+Hy2W/NIxwSgMU7XmAdiivCU3NMLeTde65BTjkXtTiJXwozFNu6990FuqXWn7e7Su486JOadGrnCQWj4wt+ikwhphRnaTljVcbfDX1M+EO6nw4U/kwTalW6R/x64mCRyqd2M4+FeOqnQUCUd44/ZYE=
cache: apt
